### PR TITLE
Additional Delete Options for Windows OS - Move to Recycle Bin

### PR DESCRIPTION
**Pull request by ItsMeAshiq**
This change adds a new option for Windows users to optionally select to move the selected files to **Recycle Bin** rather **Permanently Delete** them from disk.

This way, developers (on Windows) would have a chance to restore them back when needed.
This option would be more useful than SCC option to restore, if the deleted file had uncommitted intermediate changes.

### CODE REVIEW

**Comment by Bas-vE** [comment]
Have you tested this? because when deployed, the Conditional Disable structure does not recognize the OS.

Next to that you made a typo in the case of the LVDeleteFile_Provider_OnCommand.vi. It should say LV_DELETE_FILES, but in your version it says LV_DELETE_FILE

**Comment by Bas-vE** [comment]
Also, are you using it for LV2018? because i'm thinking of moving it to LV2020 as we are no longer using older versions of labview, so it's hard to keep a system around with LV2018 installed just for this plugin

**Comment by ItsMeAshiq** [comment]
> Have you tested this? because when deployed, the Conditional Disable structure does not recognize the OS.
> 
I have tested it only in windows PC. I do not have other OSs. 
But the CDS should work fine in a deployed machine where the OS might be different. 

> Next to that you made a typo in the case of the LVDeleteFile_Provider_OnCommand.vi. It should say LV_DELETE_FILES, but in your version it says LV_DELETE_FILE

Yeah, I might have missed that one..
Will push one commit for its fix. 

> Also, are you using it for LV2018? because i'm thinking of moving it to LV2020 as we are no longer using older versions of labview, so it's hard to keep a system around with LV2018 installed just for this plugin

I actually used LV 2024 Q1 and used it's beta feature **Save Version** option to set the project to save all files into 2018 (can see an entry in project file attributes) . I chose this as the source in your branch was saved in 2018.

And I am currently using this plug in with LV 2020 (x64).

**Comment by ItsMeAshiq** [comment]
I tested the CDS in my PC, strangely CDS with OS as condition does not work as intended.

But, changing the condition to TARGET_TYPE does work,
image

**Comment by Bas-vE** [comment]
I'm going to merge this request, but i'm also going to a checkmark to the dialog to remember the choice and not ask again

**Pull request merged**
